begingroupundo;
replaceallfast "^([\\c\\\\:\\.]+)? +(\\d+): (  )?([„ |„¤|„¥|  ]*[\\cª]+)", "\\1\\t\\2\\t\\4", regular;
endgroupundo;

begingroupundo;
replaceallfast "[„ |„¤|„¥|  ]", "\\t", regular;
endgroupundo;

begingroupundo;
replaceallfast "ª", "£", regular;
endgroupundo;

begingroupundo;
replaceallfast "^([\\c\\\\:\\.]+)?\\t(\\d+)\\t(\\t*)(\\c+)(£)?", "\\1\\t\\2\\t\\4\\t\\3\\4\\5", regular;
endgroupundo;
