begingroupundo;
grep "[abc]", "*.cpp;*.c", "C:\\codes\\hmac", regular, subdir, hilight;
grep "aaa", "*.cpp;*.c", "C:\\codes\\hmac", regular, subdir, hilight;
grep "[abc]", "*.cpp;*.c", "C:\\codes\\hmac", regular, subdir, hilight;
grep "[abc]", "*.cpp;*.c", "C:\\codes\\hmac", regular, subdir, hilight;
grep "[abc]", "*.cpp;*.c", "C:\\codes\\hmac", regular, subdir, hilight;
grep "[abc]", "*.cpp;*.c", "C:\\codes\\hmac", regular, subdir, hilight;
endgroupundo;
