begingroupundo;
grepreplace "[abc]", "d", "*.cpp;*.c", "C:\\codes\\hmac", regular, subdir, hilight;
grepreplace "aaa", "cccc", "*.cpp;*.c", "C:\\codes\\hmac", regular, subdir, hilight;
grepreplace "[abc]", "d", "*.cpp;*.c", "C:\\codes\\hmac", regular, subdir, hilight;
grepreplace "[abc]", "d", "*.cpp;*.c", "C:\\codes\\hmac", regular, subdir, hilight;
grepreplace "[abc]", "d", "*.cpp;*.c", "C:\\codes\\hmac", regular, subdir, hilight;
grepreplace "[abc]", "d", "*.cpp;*.c", "C:\\codes\\hmac", regular, subdir, hilight;
endgroupundo;
